// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Todo struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Reminder             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=reminder,proto3" json:"reminder,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsCompleted          bool                 `protobuf:"varint,6,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Todo) GetReminder() *timestamp.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

func (m *Todo) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Todo) GetIsCompleted() bool {
	if m != nil {
		return m.IsCompleted
	}
	return false
}

type TodoRequest struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Reminder             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TodoRequest) Reset()         { *m = TodoRequest{} }
func (m *TodoRequest) String() string { return proto.CompactTextString(m) }
func (*TodoRequest) ProtoMessage()    {}
func (*TodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *TodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoRequest.Unmarshal(m, b)
}
func (m *TodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoRequest.Marshal(b, m, deterministic)
}
func (m *TodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoRequest.Merge(m, src)
}
func (m *TodoRequest) XXX_Size() int {
	return xxx_messageInfo_TodoRequest.Size(m)
}
func (m *TodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodoRequest proto.InternalMessageInfo

func (m *TodoRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TodoRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TodoRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TodoRequest) GetReminder() *timestamp.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type TodoResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoResponse) Reset()         { *m = TodoResponse{} }
func (m *TodoResponse) String() string { return proto.CompactTextString(m) }
func (*TodoResponse) ProtoMessage()    {}
func (*TodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *TodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoResponse.Unmarshal(m, b)
}
func (m *TodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoResponse.Marshal(b, m, deterministic)
}
func (m *TodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoResponse.Merge(m, src)
}
func (m *TodoResponse) XXX_Size() int {
	return xxx_messageInfo_TodoResponse.Size(m)
}
func (m *TodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TodoResponse proto.InternalMessageInfo

func (m *TodoResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *TodoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListTodoRequest struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListTodoRequest) Reset()         { *m = ListTodoRequest{} }
func (m *ListTodoRequest) String() string { return proto.CompactTextString(m) }
func (*ListTodoRequest) ProtoMessage()    {}
func (*ListTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *ListTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoRequest.Unmarshal(m, b)
}
func (m *ListTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoRequest.Marshal(b, m, deterministic)
}
func (m *ListTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoRequest.Merge(m, src)
}
func (m *ListTodoRequest) XXX_Size() int {
	return xxx_messageInfo_ListTodoRequest.Size(m)
}
func (m *ListTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoRequest proto.InternalMessageInfo

func (m *ListTodoRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListTodoRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ListTodoRequest) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ListTodoRequest) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type ListTodoResponse struct {
	TodoList             []*Todo  `protobuf:"bytes,1,rep,name=todoList,proto3" json:"todoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodoResponse) Reset()         { *m = ListTodoResponse{} }
func (m *ListTodoResponse) String() string { return proto.CompactTextString(m) }
func (*ListTodoResponse) ProtoMessage()    {}
func (*ListTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *ListTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodoResponse.Unmarshal(m, b)
}
func (m *ListTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodoResponse.Marshal(b, m, deterministic)
}
func (m *ListTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodoResponse.Merge(m, src)
}
func (m *ListTodoResponse) XXX_Size() int {
	return xxx_messageInfo_ListTodoResponse.Size(m)
}
func (m *ListTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodoResponse proto.InternalMessageInfo

func (m *ListTodoResponse) GetTodoList() []*Todo {
	if m != nil {
		return m.TodoList
	}
	return nil
}

type UpdatedTodoRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Todo                 *Todo    `protobuf:"bytes,2,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatedTodoRequest) Reset()         { *m = UpdatedTodoRequest{} }
func (m *UpdatedTodoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatedTodoRequest) ProtoMessage()    {}
func (*UpdatedTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{5}
}

func (m *UpdatedTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatedTodoRequest.Unmarshal(m, b)
}
func (m *UpdatedTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatedTodoRequest.Marshal(b, m, deterministic)
}
func (m *UpdatedTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatedTodoRequest.Merge(m, src)
}
func (m *UpdatedTodoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatedTodoRequest.Size(m)
}
func (m *UpdatedTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatedTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatedTodoRequest proto.InternalMessageInfo

func (m *UpdatedTodoRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdatedTodoRequest) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type UpdatedTodoResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatedTodoResponse) Reset()         { *m = UpdatedTodoResponse{} }
func (m *UpdatedTodoResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatedTodoResponse) ProtoMessage()    {}
func (*UpdatedTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{6}
}

func (m *UpdatedTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatedTodoResponse.Unmarshal(m, b)
}
func (m *UpdatedTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatedTodoResponse.Marshal(b, m, deterministic)
}
func (m *UpdatedTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatedTodoResponse.Merge(m, src)
}
func (m *UpdatedTodoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatedTodoResponse.Size(m)
}
func (m *UpdatedTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatedTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatedTodoResponse proto.InternalMessageInfo

func (m *UpdatedTodoResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdatedTodoResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdatedTodoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteTodoRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoRequest) Reset()         { *m = DeleteTodoRequest{} }
func (m *DeleteTodoRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoRequest) ProtoMessage()    {}
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{7}
}

func (m *DeleteTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoRequest.Unmarshal(m, b)
}
func (m *DeleteTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoRequest.Merge(m, src)
}
func (m *DeleteTodoRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoRequest.Size(m)
}
func (m *DeleteTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoRequest proto.InternalMessageInfo

func (m *DeleteTodoRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteTodoRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteTodoResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoResponse) Reset()         { *m = DeleteTodoResponse{} }
func (m *DeleteTodoResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoResponse) ProtoMessage()    {}
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{8}
}

func (m *DeleteTodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoResponse.Unmarshal(m, b)
}
func (m *DeleteTodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoResponse.Merge(m, src)
}
func (m *DeleteTodoResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoResponse.Size(m)
}
func (m *DeleteTodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoResponse proto.InternalMessageInfo

func (m *DeleteTodoResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteTodoResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteTodoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Todo)(nil), "v1.Todo")
	proto.RegisterType((*TodoRequest)(nil), "v1.TodoRequest")
	proto.RegisterType((*TodoResponse)(nil), "v1.TodoResponse")
	proto.RegisterType((*ListTodoRequest)(nil), "v1.ListTodoRequest")
	proto.RegisterType((*ListTodoResponse)(nil), "v1.ListTodoResponse")
	proto.RegisterType((*UpdatedTodoRequest)(nil), "v1.UpdatedTodoRequest")
	proto.RegisterType((*UpdatedTodoResponse)(nil), "v1.UpdatedTodoResponse")
	proto.RegisterType((*DeleteTodoRequest)(nil), "v1.DeleteTodoRequest")
	proto.RegisterType((*DeleteTodoResponse)(nil), "v1.DeleteTodoResponse")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x65, 0xed, 0xb4, 0x71, 0xc6, 0x15, 0x0d, 0xdb, 0x52, 0x2c, 0x0b, 0x09, 0x63, 0x71, 0xf0,
	0xc9, 0xa5, 0xe1, 0xab, 0x5c, 0x40, 0x88, 0x1e, 0x11, 0x02, 0x53, 0xce, 0x95, 0xeb, 0x1d, 0xaa,
	0x95, 0x92, 0xac, 0xf1, 0x6e, 0xc2, 0xaf, 0xe0, 0x77, 0xf0, 0xc7, 0xf8, 0x0f, 0x5c, 0xd1, 0xee,
	0x7a, 0xdd, 0x24, 0x16, 0x44, 0x88, 0x43, 0x6f, 0xd9, 0x37, 0x6f, 0x26, 0xef, 0xbd, 0x19, 0x03,
	0x28, 0xc1, 0x44, 0x5e, 0x37, 0x42, 0x09, 0xea, 0x2d, 0x4f, 0xe2, 0x07, 0x57, 0x42, 0x5c, 0x4d,
	0xf1, 0xd8, 0x20, 0x97, 0x8b, 0x2f, 0xc7, 0x8a, 0xcf, 0x50, 0xaa, 0x72, 0x56, 0x5b, 0x52, 0xfa,
	0x93, 0xc0, 0xe0, 0x5c, 0x30, 0x41, 0x6f, 0x83, 0xc7, 0x59, 0x44, 0x12, 0x92, 0xf9, 0x85, 0xc7,
	0x19, 0x3d, 0x84, 0x1d, 0xc5, 0xd5, 0x14, 0x23, 0x2f, 0x21, 0xd9, 0xa8, 0xb0, 0x0f, 0x9a, 0x40,
	0xc8, 0x50, 0x56, 0x0d, 0xaf, 0x15, 0x17, 0xf3, 0xc8, 0x37, 0xb5, 0x55, 0x88, 0x3e, 0x87, 0xa0,
	0xc1, 0x19, 0x9f, 0x33, 0x6c, 0xa2, 0x41, 0x42, 0xb2, 0x70, 0x12, 0xe7, 0x56, 0x44, 0xee, 0x44,
	0xe4, 0xe7, 0x4e, 0x44, 0xd1, 0x71, 0xe9, 0x4b, 0x80, 0xaa, 0xc1, 0x52, 0x21, 0xbb, 0x28, 0x55,
	0xb4, 0xb3, 0xb5, 0x73, 0xd4, 0xb2, 0xdf, 0x28, 0xfa, 0x10, 0xf6, 0xb8, 0xbc, 0xa8, 0xc4, 0xac,
	0x9e, 0xa2, 0x42, 0x16, 0xed, 0x26, 0x24, 0x0b, 0x8a, 0x90, 0xcb, 0xb7, 0x0e, 0x4a, 0xbf, 0x13,
	0x08, 0xb5, 0xcd, 0x02, 0xbf, 0x2e, 0x50, 0xaa, 0x9b, 0x76, 0x9b, 0x3e, 0x86, 0x3d, 0x2b, 0x47,
	0xd6, 0x62, 0x2e, 0x91, 0x8e, 0xc1, 0x2f, 0x6b, 0x6e, 0x04, 0x8d, 0x0a, 0xfd, 0xb3, 0x55, 0xe8,
	0x39, 0x85, 0xe9, 0x0f, 0x02, 0xfb, 0xef, 0xb8, 0x54, 0xff, 0xee, 0xe2, 0x14, 0x46, 0x52, 0x95,
	0x8d, 0xd2, 0x3a, 0x8c, 0x87, 0x2d, 0xc1, 0x76, 0x64, 0xfa, 0x14, 0x86, 0x38, 0x67, 0xa6, 0x6f,
	0xbb, 0x39, 0x47, 0x4d, 0x4f, 0x61, 0x7c, 0x2d, 0xb4, 0xf5, 0xf7, 0x08, 0x02, 0x7d, 0x99, 0x1a,
	0x8f, 0x48, 0xe2, 0x67, 0xe1, 0x24, 0xc8, 0x97, 0x27, 0xb9, 0xe1, 0x74, 0x95, 0xf4, 0x0c, 0xe8,
	0xe7, 0x9a, 0xe9, 0xad, 0xae, 0xba, 0xec, 0x67, 0x73, 0x1f, 0x06, 0xba, 0xc7, 0xd8, 0x5c, 0x9d,
	0x64, 0xd0, 0xf4, 0x23, 0x1c, 0xac, 0x4d, 0xf9, 0x63, 0xc4, 0x11, 0x0c, 0xe5, 0xa2, 0xaa, 0x50,
	0x4a, 0x33, 0x29, 0x28, 0xdc, 0xb3, 0x0d, 0xd6, 0xef, 0xc2, 0x7f, 0x06, 0x77, 0xce, 0x50, 0x5f,
	0xd2, 0xdf, 0x75, 0x6d, 0xee, 0xec, 0x03, 0xd0, 0xd5, 0xb6, 0xff, 0x17, 0x32, 0xf9, 0xd5, 0xde,
	0xf1, 0x27, 0x6c, 0x96, 0xbc, 0x42, 0x9a, 0xc3, 0xf0, 0x3d, 0x7e, 0x33, 0x1f, 0xf0, 0x7e, 0x17,
	0x83, 0xd5, 0x17, 0x8f, 0xaf, 0x01, 0xfb, 0xcf, 0xe9, 0x2d, 0xfa, 0x02, 0x02, 0xb7, 0x1b, 0x7a,
	0xa0, 0xeb, 0x1b, 0x27, 0x15, 0x1f, 0xae, 0x83, 0x5d, 0xe3, 0x6b, 0x00, 0x1b, 0xaa, 0x69, 0x3d,
	0xd2, 0xac, 0xfe, 0xaa, 0xe2, 0x7b, 0x3d, 0xbc, 0x1b, 0xf0, 0x0a, 0x42, 0x9b, 0x85, 0x29, 0xd0,
	0xbb, 0x9a, 0xd9, 0xcb, 0x34, 0x3e, 0xda, 0x84, 0x5d, 0xff, 0xe5, 0xae, 0x39, 0xb9, 0x27, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x13, 0xe9, 0x1c, 0xe2, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	NewTodo(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error)
	ListTodo(ctx context.Context, in *ListTodoRequest, opts ...grpc.CallOption) (*ListTodoResponse, error)
	UpdateTodo(ctx context.Context, in *UpdatedTodoRequest, opts ...grpc.CallOption) (*UpdatedTodoResponse, error)
	DeletedTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*DeleteTodoResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) NewTodo(ctx context.Context, in *TodoRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := c.cc.Invoke(ctx, "/v1.TodoService/NewTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) ListTodo(ctx context.Context, in *ListTodoRequest, opts ...grpc.CallOption) (*ListTodoResponse, error) {
	out := new(ListTodoResponse)
	err := c.cc.Invoke(ctx, "/v1.TodoService/ListTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) UpdateTodo(ctx context.Context, in *UpdatedTodoRequest, opts ...grpc.CallOption) (*UpdatedTodoResponse, error) {
	out := new(UpdatedTodoResponse)
	err := c.cc.Invoke(ctx, "/v1.TodoService/UpdateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) DeletedTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*DeleteTodoResponse, error) {
	out := new(DeleteTodoResponse)
	err := c.cc.Invoke(ctx, "/v1.TodoService/DeletedTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	NewTodo(context.Context, *TodoRequest) (*TodoResponse, error)
	ListTodo(context.Context, *ListTodoRequest) (*ListTodoResponse, error)
	UpdateTodo(context.Context, *UpdatedTodoRequest) (*UpdatedTodoResponse, error)
	DeletedTodo(context.Context, *DeleteTodoRequest) (*DeleteTodoResponse, error)
}

// UnimplementedTodoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServiceServer struct {
}

func (*UnimplementedTodoServiceServer) NewTodo(ctx context.Context, req *TodoRequest) (*TodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTodo not implemented")
}
func (*UnimplementedTodoServiceServer) ListTodo(ctx context.Context, req *ListTodoRequest) (*ListTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTodo not implemented")
}
func (*UnimplementedTodoServiceServer) UpdateTodo(ctx context.Context, req *UpdatedTodoRequest) (*UpdatedTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTodo not implemented")
}
func (*UnimplementedTodoServiceServer) DeletedTodo(ctx context.Context, req *DeleteTodoRequest) (*DeleteTodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletedTodo not implemented")
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_NewTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).NewTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TodoService/NewTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).NewTodo(ctx, req.(*TodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_ListTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).ListTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TodoService/ListTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).ListTodo(ctx, req.(*ListTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_UpdateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatedTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).UpdateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TodoService/UpdateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).UpdateTodo(ctx, req.(*UpdatedTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_DeletedTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).DeletedTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TodoService/DeletedTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).DeletedTodo(ctx, req.(*DeleteTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewTodo",
			Handler:    _TodoService_NewTodo_Handler,
		},
		{
			MethodName: "ListTodo",
			Handler:    _TodoService_ListTodo_Handler,
		},
		{
			MethodName: "UpdateTodo",
			Handler:    _TodoService_UpdateTodo_Handler,
		},
		{
			MethodName: "DeletedTodo",
			Handler:    _TodoService_DeletedTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
